### ISSUE TITLE
Proxy to deep URL

### ISSUE THREAD

**Issue by allavena** [pact-foundation/pact-provider-proxy#5]
My provider runs on https://provider.com/long/url/that/I/pass/serivce.json
The calls are proxied to /service.json.

In other words, in the rake task, I've set
task.provider_base_url 'http://localhost:3000/long/url/'
my mock is for /service.json
and running the proxy verify, the calls are sent to http://localhost:3000/service.json'
I think they should be sent to 'http://localhost:3000/long/url/service.json'

PS: on my case, I have a work around, I have a config value for service.json, I'll just set the comple path there.

**Comment by bethesque** [comment]
Sorry, only just seen this. For some reason, notification weren't turned on for this repo. So, the problem is, the path after the host is being ignored when concatenating the base url and the request path?

**Comment by allavena** [comment]
I don't remember, to be honest. I know I had had some issues, and fixed it. 
My mock is to localhost:1234/long_url/with/full/path
I have in my verification code:  task.provider_base_url 'https://long_url/with/full/path'  [and the doc says nothing about supporting a full path].
I've checked, my verification also works with task.provider_base_url 'https://long_url/with/full/path'

Option 1, there was an issue, and it got fixed.
Option 2, there is an issue, can't reproduce. 
Option 3, I was running my mock on localhost:1234/path, and was complaining that a non-existing feature (verifying with task.provider_base_url 'https://long_url/with/full/path'). 

Eitherway, close?

**Comment by bethesque** [comment]
Yup, let's close. Thanks.
