### ISSUE TITLE
query parameter will be url decoded before pact-provider-proxy sends provider request

### ISSUE THREAD

**Issue by gwittchen** [pact-foundation/pact-provider-proxy#6]
We are using pact-provider-proxy to test our service API.
In one of the pact states we defined a GET request with already encoded query parameter as string.

However when we run our pact test we noticed that the pact-proxy is sending the query parameter url-decode! 
Example pact file.

``` json
{  
   "consumer":{  
      "name":"serviceA"
   },
   "provider":{  
      "name":"serviceB"
   },
   "interactions":[  
      {  
         "description":"A serviceB request value SYD",
         "provider_state":"no values exists",
         "request":{  
            "method":"get",
            "path":"/details",
            "query":"bookingDuration=1&bookingDate=2016-01-05&locations%5Bpickup%5D%5BcityCode%5D=SYD",
            "headers":{  
               "Accept":"application/json"
            }
         },
         "response":{  
            "status":200,
            "headers":{  
               "Content-Type":"application/json; charset=utf-8"
            },
            "body":[  

            ]
         }
      }
   ],
   "metadata":{  
      "pactSpecificationVersion":"2.0.0"
   }
}
```

Expected GET request
http://locathost:3013/details?bookingDuration=1&bookingDate=2016-01-05&locations%5Bpickup%5D%5BcityCode%5D=SYD

Received GET request
http://localhost:3013/details?bookingDuration=1&bookingDate=2016-01-05&locations[pickup][cityCode]=SYD

We would have expected that, when we provide a already encoded query string that it's been used as is. For some reasons the query string is been url decoded.

we are using pact-provider-proxy-2.1.0.

**Comment by bethesque** [comment]
So sorry @gwittchen for some reason, I didn't have notifications turned on for the repo. Did you find a fix for this? @uglyog I remember we went back and forward on what to do about encoding, can you remember what we decided? From vague memory, we decided to encode it in the pact if it was a string, but not if it was a hash.

**Comment by uglyog** [comment]
That is correct, string form should be encoded but the hash form does not.

**Comment by gwittchen** [comment]
Hi @bethesque, we ended up changing the api from a GET to POST to work around this issue. We haven't tested it since.
