### ISSUE TITLE
Cannot verify provider state with remote url

### ISSUE THREAD

**Issue by eskimoquinn** [pact-foundation/pact-provider-proxy#7]
I am trying to verify a Pact for a remote service using this library. I have created my provider states and my pact has the provider state. However, I keep getting the error message:

> Could not find one or more provider states.
> Have you required the provider states file for this consumer in your pact_helper.rb?
> If you have not yet defined these states, here is a template:

Here is the RAKEFILE: 

```
require '../licensing-service-integration/spec/service_consumers/provider_states_for_som'


Pact::ProxyVerificationTask.new :pact_demo do | task |
  pact_url = 'https://username:password@ithaka.pact.dius.com.au/pacts/provider/licensing-service/consumer/som/latest'
  task.pact_url pact_url
  task.provider_base_url 'http://licensing-service.apps.test.cirrostratus.org' #scheme, host and optional port
end
```
provider_states_for_som.rb:
```require 'pact/provider/rspec'

 Pact.provider_states_for "som" do

  provider_state "an account with an active license" do
    set_up do
      no_op
    end
    puts 'set-up ======='
  end

end
```

And finally, here is the PACT:

```
{
  "provider": {
    "name": "licensing-service"
  },
  "consumer": {
    "name": "som"
  },
  "interactions": [
    {
      "description": "a cancel request",
      "request": {
        "method": "POST",
        "path": "/v0/cancelAccess",
        "headers": {
          "Accept": "application/json",
          "Content-Type": "application/json"
        },
        "body": {
          "accountExternalId": "1234",
          "offerCode": "offer-standard",
          "orderLineNumbers": [
            "5678"
          ],
          "orderNumber": "1234"
        }
      },
      "response": {
        "status": 200,
        "body": [
          {
            "licenseId": "a3996763-35f5-4981-831e-a76ada7b03fd",
            "licenseStatus": "CANCELLED"
          }
        ]
      },
      "providerState": "an account with an active license"
    }, 
...
```

**Comment by uglyog** [comment]
Just a guess, but the provider states should be for the provider name:

```ruby
 Pact.provider_states_for "som" do # <-- Should this be "licensing-service"?

  provider_state "an account with an active license" do
    set_up do
      no_op
    end
    puts 'set-up ======='
  end

end
```

**Comment by eskimoquinn** [comment]
Thanks, but tried that. The error message seems to indicate it is looking for a provider state which looks identical to mine:
```
Could not find one or more provider states.
Have you required the provider states file for this consumer in your pact_helper.rb?
If you have not yet defined these states, here is a template:

Pact.provider_states_for "som" do

  provider_state "an account with an active license" do
    set_up do
      # Your set up code goes here
    end
  end

end
```

**Comment by eskimoquinn** [comment]
It looks like I need to explicitly declare the pact helper in the rakefile?
```
 :pact_helper => '.pact_states.rb'
``` 
Would not work otherwise.

**Comment by bethesque** [comment]
Yeah, due to [this](https://github.com/pact-foundation/pact-provider-proxy/issues/2) issue, the pact helper is not automatically loaded. It must be explicitly required. The documentation is on the README.


> Specifying a pact_helper is optional, and is only required if you are using provider states or you need to configure Pact. Note that the pact_helper for the ProxyVerificationTask will not be automatically loaded like it is for the regular pact:verify - you must specify the path yourself if you need one (see the example below). The configuration options for the provider code will be different from the consumer code, so you cannot reuse the pact_helper from your consumer tests.
